- hosts: genome
  vars:
    target_user: monarch
    apollo_version: 2.0.2
  tasks:
  - name: Download the Apollo release
    get_url: url=https://github.com/GMOD/Apollo/archive/{{ apollo_version }}.zip dest=/tmp/{{ apollo_version }}.zip

  # not using unarchive because of https://github.com/ansible/ansible-modules-core/issues/932
  - name: unzip the archive
    shell: sudo unzip /tmp/{{ apollo_version }}.zip -d /opt

  - name: saving conf file
    copy: src=/opt/apollo/apollo-config.groovy dest=/tmp/apollo-config.groovy remote_src=true

  - name: delete current apollo directory
    shell: sudo rm -rf /opt/apollo

  - name: rename folder
    shell: sudo mv /opt/Apollo-{{ apollo_version }} /opt/apollo

  - name: chown
    command: sudo chown -R {{ target_user }}:{{ target_user }} /opt/apollo

  - name: copy conf file
    command: mv /tmp/apollo-config.groovy /opt/apollo/apollo-config.groovy

  - name: package apollo
    command: bash -c "cd /opt/apollo && ./apollo deploy"

  - name: stop tomcat
    shell : sudo service tomcat7 stop

  - name: remove old version on tomcat
    shell: sudo rm -rf /var/lib/tomcat7/webapps/apollo/ && sudo rm -f /var/lib/tomcat7/webapps/apollo.war

  - name: move war
    command: sudo mv /opt/apollo/target/apollo-{{ apollo_version }}.war /var/lib/tomcat7/webapps/apollo.war

  - name: restart tomcat
    shell : sudo service tomcat7 restart
